//Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

//Register
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//Profile
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

//Admin
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

//create slot
export const CREATE_SLOT_REQUEST = 'CREATE_SLOT_REQUEST';
export const CREATE_SLOT_SUCCESS = 'CREATE_SLOT_SUCCESS';
export const CREATE_SLOT_FAIL = 'CREATE_SLOT_FAIL';

//BOOK SLOT
export const BOOK_SLOT_REQUEST = 'BOOK_SLOT_REQUEST';
export const BOOK_SLOT_SUCCESS = 'BOOK_SLOT_SUCCESS';
export const BOOK_SLOT_FAIL = 'BOOK_SLOT_FAIL';

//GET SLOTS BY DATE
export const SLOT_DETAILS_REQUEST = 'SLOT_DETAILS_REQUEST';
export const SLOT_DETAILS_SUCCESS = 'SLOT_DETAILS_SUCCESS';
export const SLOT_DETAILS_FAIL = 'SLOT_DETAILS_FAIL';

//get number of slots by date
export const NUM_OF_SLOT_DETAILS_FAIL = 'NUM_OF_SLOT_DETAILS_FAIL';
export const NUM_OF_SLOT_DETAILS_REQUEST = 'NUM_OF_SLOT_DETAILS_REQUEST';
export const NUM_OF_SLOT_DETAILS_SUCCESS = 'NUM_OF_SLOT_DETAILS_SUCCESS';

//update slot details
export const UPDATE_SLOT_FAIL = 'UPDATE_SLOT_FAIL';
export const UPDATE_SLOT_REQUEST = 'UPDATE_SLOT_REQUEST';
export const UPDATE_SLOT_SUCCESS = 'UPDATE_SLOT_SUCCESS';

//get my slots
export const GET_MY_SLOT_FAIL = 'GET_MY_SLOT_FAIL';
export const GET_MY_SLOT_REQUEST = 'GET_MY_SLOT_REQUEST';
export const GET_MY_SLOT_SUCCESS = 'GET_MY_SLOT_SUCCESS';
